In [1]:
print("Hello")

Hello

In [3]:
## Objective: Get the raw data from Yfinance and store it in csv file in data folder
import yfinance as yf
import os

In [9]:
US_tickers=  ['TSLA', 'META', 'NVDA', 'PLTR', 'INTC']
indian_tickers = ['TATAMOTORS.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS']

In [6]:
# fetch just one ticker to test
data = yf.download('AAPL', period= '3y', interval= '1d')
data

C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\1030179250.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('AAPL', period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2022-09-30  136.052338  140.876200  135.855449  139.084476  124925300
2022-10-03  140.236313  140.846688  135.550289  136.062212  114311700
2022-10-04  143.829590  143.947720  142.018172  142.776211   87830100
2022-10-05  144.124893  145.089675  140.787575  141.831115   79471000
2022-10-06  143.169983  145.247194  142.963255  143.544082   68402200
...                ...         ...         ...         ...        ...
2025-09-24  252.309998  255.740005  251.039993  255.220001   42303700
2025-09-25  256.869995  257.170013  251.710007  253.210007   55202100
2025-09-26  255.460007  257.600006  253.779999  254.100006   46076300
2025-09-29  254.429993  255.000000  253.009995  254.559998   40091100
2025-09-30  254.529999  255.919006  253.820099  254.824997   12178240

[752 rows x 5 columns]

In [8]:
# get indian stock data
ind_data = yf.download('TATAMotors.NS', period= '3y', interval= '1d')
ind_data

C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\1352516258.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ind_data = yf.download('TATAMotors.NS', period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,TATAMOTORS.NS,TATAMOTORS.NS,TATAMOTORS.NS,TATAMOTORS.NS,TATAMOTORS.NS
Date,,,,,
2022-09-30,398.674316,402.270853,386.751525,392.170973,20951277
2022-10-03,391.826111,400.595758,389.707605,399.561148,20332430
2022-10-04,401.925964,402.960604,396.999193,400.053797,12761425
2022-10-06,408.035187,411.533182,403.502551,403.601093,12771199
2022-10-07,406.113708,407.936620,402.714255,407.345401,10670854
...,...,...,...,...,...
2025-09-24,682.950012,703.299988,681.299988,700.500000,13252215
2025-09-25,664.299988,675.000000,655.299988,669.900024,24687611
2025-09-26,672.900024,680.349976,662.349976,666.000000,15780434
2025-09-29,672.500000,685.000000,670.000000,684.000000,13014474
2025-09-30,680.200012,683.500000,666.650024,672.000000,14989597

In [10]:
# get all the data of just 5 stocks each from US and India and store it in data folder
data_folder = '../data/raw/us_stocks'
os.makedirs(data_folder, exist_ok=True)
for ticker in US_tickers:
    data = yf.download(ticker, period= '3y', interval= '1d')
    data.to_csv(os.path.join(data_folder, f'{ticker}.csv'))

C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2284200294.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2284200294.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2284200294.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2284200294.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2284200294.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed

In [11]:
data_folder = '../data/raw/indian_stocks'
os.makedirs(data_folder, exist_ok=True)
for ticker in indian_tickers:
    data = yf.download(ticker, period= '3y', interval= '1d')
    data.to_csv(os.path.join(data_folder, f'{ticker}.csv'))

C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2258725153.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2258725153.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2258725153.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2258725153.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed
C:\Users\302sy\AppData\Local\Temp\ipykernel_11960\2258725153.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period= '3y', interval= '1d')
[*********************100%***********************]  1 of 1 completed

## This is old style where you copy the data into local - instead upload it to Google Cloud

In [2]:
# get the data from the yfinance and upload to google cloud bucket named as stockmarket-data

import datetime, time
import pandas as pd
from google.cloud import storage
import yfinance as yf

In [ ]:
# step 1: load the data into dataframe
df= pd.read_csv('../data/raw/us_stocks/TSLA.csv')
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,TSLA,TSLA,TSLA,TSLA,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN
2,2022-09-30,265.25,275.57000732421875,262.4700012207031,266.1499938964844,67726600
3,2022-10-03,242.39999389648438,255.16000366210938,241.00999450683594,254.5,98363500
4,2022-10-04,249.44000244140625,257.5,242.00999450683594,250.52000427246094,109578500

In [9]:
# step 2: upload the df into cloud storage service
from dotenv import load_dotenv
load_dotenv()
client = storage.Client()

In [10]:
export_bucket = client.get_bucket('stockmarket-data')
# export_blob = export_bucket.blob('raw/TSLA.csv')
# export_blob.upload_from_filename('../data/raw/us_stocks/TSLA.csv')

### The purpose of this notebook is over - testing my misc codes

In [4]:
from pathlib import Path
Path.cwd().parent

WindowsPath('s:/Scaler Projects/Automated-stockmarket-datapipeline')